version: '3'
services:
  influent-server:
    build:
      context: ../..
      dockerfile: example/Dockerfile
    environment:
      DURATION_SECONDS: '60'
      INFLUENT_LOG_LEVEL: INFO
  fluentd-agent:
    image: fluent/fluentd
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
